// Package gitssh implements the restricted RepoWolf Git SSH transport client.
package gitssh

import (
	"fmt"
	"strconv"
	"strings"
	"unicode/utf8"

	repowolfv1 "github.com/rochecompaan/repowolf/gen/repowolf/v1"
)

const (
	maximumArguments = 64
	maximumArgvBytes = 64 << 10
)

// Operation identifies one supported Git smart-protocol service.
type Operation string

const (
	UploadPack  Operation = "upload-pack"
	ReceivePack Operation = "receive-pack"
)

// Request is an untrusted typed repository selector and Git operation.
type Request struct {
	Repository *repowolfv1.RepositorySelector
	Operation  Operation
}

// Parse accepts only the exact SSH argument forms generated by Git for the two
// supported smart-protocol operations.
func Parse(args []string) (Request, error) {
	if err := validateArguments(args); err != nil {
		return Request{}, err
	}
	position := 0
	if len(args) >= 2 && args[0] == "-o" {
		if args[1] != "SendEnv=GIT_PROTOCOL" {
			return Request{}, fmt.Errorf("unsupported SSH option")
		}
		position = 2
	}
	var port uint64
	if len(args)-position >= 2 && args[position] == "-p" {
		var err error
		port, err = parsePort(args[position+1])
		if err != nil {
			return Request{}, err
		}
		position += 2
	}
	if len(args)-position != 2 {
		return Request{}, fmt.Errorf("unsupported SSH argument shape")
	}
	host, err := parseAuthority(args[position])
	if err != nil {
		return Request{}, err
	}
	operation, owner, name, err := parseCommand(args[position+1])
	if err != nil {
		return Request{}, err
	}
	return Request{
		Repository: &repowolfv1.RepositorySelector{Host: host, SshPort: uint32(port), Owner: owner, Name: name},
		Operation:  operation,
	}, nil
}

func validateArguments(args []string) error {
	if len(args) < 2 || len(args) > maximumArguments {
		return fmt.Errorf("unsupported SSH argument count")
	}
	total := 0
	for _, argument := range args {
		total += len(argument)
		if total > maximumArgvBytes || !utf8.ValidString(argument) || strings.IndexByte(argument, 0) >= 0 {
			return fmt.Errorf("invalid SSH argument data")
		}
	}
	return nil
}

func parsePort(value string) (uint64, error) {
	if value == "" {
		return 0, fmt.Errorf("invalid SSH port")
	}
	for _, character := range value {
		if character < '0' || character > '9' {
			return 0, fmt.Errorf("invalid SSH port")
		}
	}
	port, err := strconv.ParseUint(value, 10, 16)
	if err != nil || port == 0 {
		return 0, fmt.Errorf("invalid SSH port")
	}
	return port, nil
}

func parseAuthority(authority string) (string, error) {
	const prefix = "git@"
	if !strings.HasPrefix(authority, prefix) {
		return "", fmt.Errorf("unsupported SSH user")
	}
	host := authority[len(prefix):]
	if !validHost(host) {
		return "", fmt.Errorf("invalid SSH host")
	}
	return strings.ToLower(host), nil
}

func parseCommand(command string) (Operation, string, string, error) {
	for _, candidate := range []struct {
		prefix    string
		operation Operation
	}{
		{"git-upload-pack '", UploadPack},
		{"git-receive-pack '", ReceivePack},
	} {
		if !strings.HasPrefix(command, candidate.prefix) || !strings.HasSuffix(command, ".git'") {
			continue
		}
		slug := command[len(candidate.prefix) : len(command)-len(".git'")]
		parts := strings.Split(slug, "/")
		if len(parts) == 2 && validSlug(parts[0], parts[1]) {
			return candidate.operation, parts[0], parts[1], nil
		}
	}
	return "", "", "", fmt.Errorf("unsupported SSH remote command")
}

func validHost(value string) bool {
	if value == "" || len(value) > 253 || strings.HasPrefix(value, ".") || strings.HasSuffix(value, ".") {
		return false
	}
	for _, label := range strings.Split(value, ".") {
		if label == "" || len(label) > 63 || label[0] == '-' || label[len(label)-1] == '-' {
			return false
		}
		for _, character := range label {
			if !asciiAlphaNumeric(character) && character != '-' {
				return false
			}
		}
	}
	return true
}

func validSlug(owner, name string) bool {
	if owner == "" || len(owner) > 39 || name == "" || len(name) > 100 || name == "." || name == ".." {
		return false
	}
	if owner[0] == '-' || owner[len(owner)-1] == '-' || strings.Contains(owner, "--") {
		return false
	}
	for _, character := range owner {
		if !asciiAlphaNumeric(character) && character != '-' {
			return false
		}
	}
	for _, character := range name {
		if !asciiAlphaNumeric(character) && character != '.' && character != '_' && character != '-' {
			return false
		}
	}
	return true
}

func asciiAlphaNumeric(character rune) bool {
	return character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z' || character >= '0' && character <= '9'
}
